#' Run GnRH detection diagnostics
#'
#' Generates diagnostic summaries for GnRH detection results, including
#' classification metadata, threshold performance curves, and summary
#' statistics.
#'
#' This function validates required detection outputs generated by
#' \code{\link{detect_gnrh}}, reconstructs a unified diagnostics table,
#' computes total marker hits, and evaluates classification performance
#' across score thresholds using sensitivity, specificity, precision,
#' and F1 score.
#'
#' Diagnostic outputs are stored in \code{object@misc$gnrh}.
#'
#' Stored diagnostics include:
#' \describe{
#'   \item{\code{diagnostics}}{
#'   Per-cell diagnostic table containing expression, scores, marker hits,
#'   detection status, and confidence labels.}
#'   \item{\code{threshold_curve}}{
#'   Threshold performance metrics across the composite score range.}
#'   \item{\code{best_threshold}}{
#'   Threshold maximizing F1 score.}
#' }
#'
#' @param object A Seurat object previously processed with
#'   \code{\link{detect_gnrh}}.
#' @param verbose Logical. Whether to print progress messages.
#'   Default is \code{TRUE}.
#'
#' @return A Seurat object with diagnostic results stored in
#'   \code{object@misc$gnrh}.
#'
#' @details
#' Required metadata columns:
#' \itemize{
#'   \item \code{gnrh_raw}
#'   \item \code{gnrh_expr}
#'   \item \code{gnrh_score}
#'   \item \code{gnrh_status}
#'   \item \code{gnrh_core_hits}
#'   \item \code{gnrh_mig_hits}
#'   \item \code{gnrh_neuro_hits}
#'   \item \code{gnrh_confident}
#' }
#'
#' The \code{gnrh_confident} column is treated as a logical high-confidence
#' reference label. Performance metrics compare score-based predictions
#' against this reference across evenly spaced score thresholds.
#'
#' If fewer than two confidence classes are present, threshold performance
#' metrics are skipped and a warning is issued.
#'
#' Performance metrics include:
#' \itemize{
#'   \item sensitivity
#'   \item specificity
#'   \item precision
#'   \item F1 score
#' }
#'
#' @seealso
#' \code{\link{detect_gnrh}},
#' \code{\link{run_gnrh}}
#'
#' @export
gnrh_diagnostics <- function(
    object,
    verbose = TRUE
) {

  stopifnot(
    inherits(
      object,
      "Seurat"
    )
  )

  log <- .msg(
    verbose
  )

  log(
    "Running diagnostics"
  )

  md <- object[[]]

  # --------------------------------------------------------------------------- #
  # Validate stored parameters
  # --------------------------------------------------------------------------- #

  if (is.null(object@misc$gnrh_params)) {
    stop(
      "Missing `gnrh_params`; run `detect_gnrh()` first.",
      call. = FALSE
    )
  }

  # --------------------------------------------------------------------------- #
  # Validate required metadata
  # --------------------------------------------------------------------------- #

  required_cols <- c(
    "gnrh_raw",
    "gnrh_expr",
    "gnrh_score",
    "gnrh_status",
    "gnrh_core_hits",
    "gnrh_mig_hits",
    "gnrh_neuro_hits",
    "gnrh_confident"
  )

  missing_cols <- setdiff(
    required_cols,
    colnames(md)
  )

  if (length(missing_cols) > 0L) {
    stop(
      "Missing required metadata columns: ",
      paste(
        missing_cols,
        collapse = ", "
      ),
      call. = FALSE
    )
  }

  # --------------------------------------------------------------------------- #
  # Initialize diagnostics storage
  # --------------------------------------------------------------------------- #

  if (is.null(object@misc$gnrh)) {
    object@misc$gnrh <- list()
  }

  # --------------------------------------------------------------------------- #
  # Recover high-confidence reference
  #
  # gnrh_confident is now a logical vector.
  # --------------------------------------------------------------------------- #

  confident <- as.logical(
    md$gnrh_confident
  )

  # --------------------------------------------------------------------------- #
  # Unified per-cell diagnostics table
  # --------------------------------------------------------------------------- #

  diag <- data.frame(
    raw_expr = md$gnrh_raw,
    expr = md$gnrh_expr,
    score = md$gnrh_score,
    status = as.character(
      md$gnrh_status
    ),
    confident = confident,
    core_hits = md$gnrh_core_hits,
    mig_hits = md$gnrh_mig_hits,
    neuro_hits = md$gnrh_neuro_hits,
    stringsAsFactors = FALSE
  )

  rownames(diag) <- rownames(md)

  object@misc$gnrh$diagnostics <-
    diag

  # --------------------------------------------------------------------------- #
  # Total module hits
  # --------------------------------------------------------------------------- #

  object <- .make_total_hits(
    object
  )

  # --------------------------------------------------------------------------- #
  # Threshold performance curve
  # --------------------------------------------------------------------------- #

  score <- as.numeric(
    md$gnrh_score
  )

  ok <-
    is.finite(score) &
    !is.na(confident)

  score <- score[
    ok
  ]

  confident <- confident[
    ok
  ]

  # --------------------------------------------------------------------------- #
  # Verify that both reference classes are present
  # --------------------------------------------------------------------------- #

  if (
    length(score) == 0L ||
    length(unique(confident)) < 2L
  ) {

    object@misc$gnrh$threshold_curve <-
      NULL

    object@misc$gnrh$best_threshold <-
      NA_real_

    warning(
      paste0(
        "Threshold curve skipped: ",
        "`gnrh_confident` has fewer than two classes."
      ),
      call. = FALSE
    )

    return(
      object
    )
  }

  # --------------------------------------------------------------------------- #
  # Score thresholds
  # --------------------------------------------------------------------------- #

  score_range <- range(
    score,
    finite = TRUE
  )

  if (
    !all(is.finite(score_range)) ||
    diff(score_range) <= 0
  ) {

    object@misc$gnrh$threshold_curve <-
      NULL

    object@misc$gnrh$best_threshold <-
      NA_real_

    warning(
      "Threshold curve skipped: `gnrh_score` has no usable range.",
      call. = FALSE
    )

    return(
      object
    )
  }

  thresholds <- seq(
    from = score_range[[1]],
    to = score_range[[2]],
    length.out = 50L
  )

  # --------------------------------------------------------------------------- #
  # Compute threshold metrics
  # --------------------------------------------------------------------------- #

  curve <- lapply(
    thresholds,
    function(threshold) {

      predicted_positive <-
        score >= threshold

      TP <- sum(
        predicted_positive &
          confident
      )

      FP <- sum(
        predicted_positive &
          !confident
      )

      FN <- sum(
        !predicted_positive &
          confident
      )

      TN <- sum(
        !predicted_positive &
          !confident
      )

      sensitivity <-
        TP /
        (TP + FN + 1e-9)

      specificity <-
        TN /
        (TN + FP + 1e-9)

      precision <-
        TP /
        (TP + FP + 1e-9)

      F1 <-
        2 *
        precision *
        sensitivity /
        (
          precision +
            sensitivity +
            1e-9
        )

      data.frame(
        threshold = threshold,
        sensitivity = sensitivity,
        specificity = specificity,
        precision = precision,
        F1 = F1,
        stringsAsFactors = FALSE
      )
    }
  )

  curve <- do.call(
    rbind,
    curve
  )

  rownames(curve) <- NULL

  # --------------------------------------------------------------------------- #
  # Store threshold diagnostics
  # --------------------------------------------------------------------------- #

  object@misc$gnrh$threshold_curve <-
    curve

  best_index <- which.max(
    curve$F1
  )

  object@misc$gnrh$best_threshold <-
    curve$threshold[
      best_index
    ]

  roc <- data.frame(
    threshold = curve$threshold,
    sensitivity = curve$sensitivity,
    specificity = curve$specificity,
    fpr = 1 - curve$specificity,
    tpr = curve$sensitivity
  )

  roc <- roc[
    order(roc$fpr, roc$tpr),
  ]

  auc <- sum(
    diff(roc$fpr) *
      (
        head(roc$tpr, -1) +
          tail(roc$tpr, -1)
      ) / 2
  )

  object@misc$gnrh$roc <- roc
  object@misc$gnrh$auc <- auc

  object
}
