#' Run GnRH detection diagnostics
#'
#' Generates diagnostic summaries for GnRH detection results,
#' including classification metadata, threshold performance curves,
#' and summary statistics.
#'
#' This function validates required detection outputs generated by
#' \code{\link{detect_gnrh}}, reconstructs a unified diagnostics table,
#' computes total marker hits, and evaluates classification performance
#' across score thresholds using sensitivity, specificity, precision,
#' and F1 score.
#'
#' Diagnostic outputs are stored in \code{object@misc$gnrh}.
#'
#' Stored diagnostics include:
#' \describe{
#'   \item{\code{diagnostics}}{Per-cell diagnostic table containing
#'   expression, scores, marker hits, and classification labels.}
#'   \item{\code{threshold_curve}}{Threshold performance metrics across
#'   the composite score range.}
#'   \item{\code{best_threshold}}{Threshold maximizing F1 score.}
#' }
#'
#' @param object A Seurat object previously processed with
#'   \code{\link{detect_gnrh}}.
#' @param verbose Logical; print progress messages. Default is
#'   \code{TRUE}.
#'
#' @return A Seurat object with diagnostic results stored in
#'   \code{object@misc$gnrh}.
#'
#' @details
#' Required metadata columns:
#' \itemize{
#'   \item \code{gnrh_raw}
#'   \item \code{gnrh_expr}
#'   \item \code{gnrh_score}
#'   \item \code{gnrh_class}
#'   \item \code{gnrh_core_hits}
#'   \item \code{gnrh_mig_hits}
#'   \item \code{gnrh_neuro_hits}
#'   \item \code{gnrh_confident}
#' }
#'
#' If fewer than two confident classes are present, threshold performance
#' metrics are skipped and a warning is issued.
#'
#' Performance metrics are computed across evenly spaced thresholds:
#' \itemize{
#'   \item sensitivity
#'   \item specificity
#'   \item precision
#'   \item F1 score
#' }
#'
#' @seealso
#' \code{\link{detect_gnrh}},
#' \code{\link{run_gnrh}}
#'
#' @export
gnrh_diagnostics <- function(
    object,
    verbose = TRUE
) {

  log <- .msg(verbose)

  log("Running diagnostics")

  md <- object[[]]

  if (is.null(object@misc$gnrh_params)) {
    stop("Missing gnrh_params (run detect_gnrh first)")
  }

  # validate required columns
  required_cols <- c(
    "gnrh_raw",
    "gnrh_expr",
    "gnrh_score",
    "gnrh_core_hits",
    "gnrh_mig_hits",
    "gnrh_neuro_hits",
    "gnrh_confident"
  )

  missing_cols <- setdiff(required_cols, colnames(md))

  if (length(missing_cols) > 0) {
    stop(
      "Missing required metadata columns: ",
      paste(missing_cols, collapse = ", ")
    )
  }

  # recover confident
  confident <- md$gnrh_confident

  confident <- factor(
    as.character(confident),
    levels = c("neg", "pos")
  )


  # unified diagnostics table
  diag <- data.frame(
    raw_expr   = md$gnrh_raw,
    expr       = md$gnrh_expr,
    score      = md$gnrh_score,
    status     = md$gnrh_status,
    confident  = md$gnrh_confident,
    core_hits  = md$gnrh_core_hits,
    mig_hits   = md$gnrh_mig_hits,
    neuro_hits = md$gnrh_neuro_hits,
    stringsAsFactors = FALSE
  )


  object@misc$gnrh$diagnostics <- diag

  # Make total hits
  object <- .make_total_hits(object)

  # threshold curve
  score <- md$gnrh_score

  ok <- is.finite(score) &
    !is.na(score) &
    !is.na(confident)

  score <- score[ok]
  confident <- confident[ok]

  if (length(unique(confident)) < 2) {

    warning(
      "ROC/curve skipped: confident has <2 classes"
    )

    return(object)
  }

  thresholds <- seq(
    min(score),
    max(score),
    length.out = 50
  )

  curve <- lapply(thresholds, function(t) {

    pred <- score >= t

    confident_bin <- confident == "pos"

    TP <- sum(pred & confident_bin)
    FP <- sum(pred & !confident_bin)
    FN <- sum(!pred & confident_bin)
    TN <- sum(!pred & !confident_bin)

    sens <- TP / (TP + FN + 1e-9)
    spec <- TN / (TN + FP + 1e-9)
    prec <- TP / (TP + FP + 1e-9)
    F1 <- 2 * prec * sens /
      (prec + sens + 1e-9)

    data.frame(
      threshold   = t,
      sensitivity = sens,
      specificity = spec,
      precision   = prec,
      F1          = F1
    )
  })

  curve <- do.call(rbind, curve)

  object@misc$gnrh$threshold_curve <- curve

  object@misc$gnrh$best_threshold <-
    curve$threshold[which.max(curve$F1)]

  object
}
