# ============================================================================= #
# Marker-program helpers
# ============================================================================= #

#' Safely extract table column
#'
#' @keywords internal
#' @noRd
.marker_safe_col <- function(
    x,
    column,
    default = NA
) {
  if (column %in% colnames(x))
    return(x[[column]])

  rep(default, nrow(x))
}


#' Convert arbitrary values to logical
#'
#' @keywords internal
#' @noRd
.marker_as_logical <- function(x) {
  if (is.logical(x)) {
    out <- x

  } else if (is.numeric(x)) {
    out <- is.finite(x) & x > 0

  } else {
    out <- tolower(
      trimws(
        as.character(x)
      )
    ) %in% c(
      "true",
      "t",
      "yes",
      "y",
      "1",
      "positive",
      "pos"
    )
  }

  out[is.na(out)] <- FALSE
  out
}


#' Compute marker evidence score
#'
#' @keywords internal
#' @noRd
.marker_evidence_score <- function(df) {
  # Prefer scores generated by the newer marker-discovery engine.
  for (column in c(
    "final_score",
    "marker_score",
    "specificity_score"
  )) {
    if (column %in% colnames(df)) {
      x <- suppressWarnings(
        as.numeric(df[[column]])
      )

      x[!is.finite(x)] <- 0

      if (any(x > 0))
        return(x)
    }
  }

  fc <- suppressWarnings(
    as.numeric(
      .marker_safe_col(
        df,
        "avg_log2FC",
        0
      )
    )
  )

  pct1 <- suppressWarnings(
    as.numeric(
      .marker_safe_col(
        df,
        "pct.1",
        0
      )
    )
  )

  pct2 <- suppressWarnings(
    as.numeric(
      .marker_safe_col(
        df,
        "pct.2",
        0
      )
    )
  )

  padj <- suppressWarnings(
    as.numeric(
      .marker_safe_col(
        df,
        "p_val_adj",
        1
      )
    )
  )

  fc[!is.finite(fc)] <- 0
  pct1[!is.finite(pct1)] <- 0
  pct2[!is.finite(pct2)] <- 0
  padj[!is.finite(padj)] <- 1

  significance <- pmin(
    -log10(
      pmax(
        padj,
        .Machine$double.xmin
      )
    ),
    50
  )

  score <-
    pmax(fc, 0) *
    pmax(pct1 - pct2, 0) *
    sqrt(pmax(pct1, 0)) *
    significance

  score[!is.finite(score)] <- 0
  score
}


#' Assign genes to curated programs
#'
#' @keywords internal
#' @noRd
.assign_marker_programs <- function(
    genes,
    developmental_modules,
    secretory_module
) {
  genes <- unique(
    toupper(
      as.character(genes)
    )
  )

  modules <- c(
    developmental_modules,
    list(secretory = secretory_module)
  )

  dimension <- c(
    stats::setNames(
      rep(
        "developmental",
        length(developmental_modules)
      ),
      names(developmental_modules)
    ),
    secretory = "functional"
  )

  rows <- lapply(
    names(modules),
    function(program) {
      hit <- intersect(
        genes,
        toupper(modules[[program]])
      )

      if (!length(hit))
        return(NULL)

      data.frame(
        gene = hit,
        program = program,
        program_dimension =
          dimension[[program]],
        stringsAsFactors = FALSE
      )
    }
  )

  rows <- Filter(
    Negate(is.null),
    rows
  )

  if (!length(rows)) {
    return(
      data.frame(
        gene = character(0),
        program = character(0),
        program_dimension = character(0),
        stringsAsFactors = FALSE
      )
    )
  }

  do.call(
    rbind,
    rows
  )
}



# ========================================================================= #
# GnRH marker programs
# ========================================================================= #
#' Classify GnRH marker candidates into biological programs
#'
#' @param files Named character vector containing marker table paths.
#' @param results Result returned by \code{\link{gnrh_gene_upset}}.
#' @param outdir Output directory.
#' @param modules Developmental modules.
#' @param secretory_module Functional secretory program.
#' @param coexpr_col Optional GNRH1 co-expression column.
#' @param gene_col Gene column.
#' @param min_medium_score Minimum marker evidence score for medium confidence.
#' @param min_high_score Minimum marker evidence score for high confidence.
#' @param min_high_datasets Minimum datasets supporting a high-confidence gene.
#' @param min_medium_datasets Minimum datasets supporting a medium-confidence gene.
#' @param include_gnrh1 Include GNRH1 as reference gene.
#' @param write_output Write TSV outputs.
#'
#' @return Named marker-program result list.
#'
#' @export
gnrh_marker_programs <- function(
    files,
    results,
    outdir,
    modules = gnrh_stage_modules(),
    secretory_module = gnrh_secretory_marker_module(),
    coexpr_col = "coexpr_flag",
    gene_col = "gene",
    min_medium_score = 0.25,
    min_high_score = 1,
    min_high_datasets = 2L,
    min_medium_datasets = 1L,
    include_gnrh1 = TRUE,
    write_output = TRUE
) {
  # ========================================================================= #
  # Validation
  # ========================================================================= #
  .validate_named_files(files, "files")
  if (!is.list(results)) {
    stop("`results` must be returned by `gnrh_gene_upset()`.", call. = FALSE)
  }
  if (!is.list(modules) || !length(modules) || is.null(names(modules))) {
    stop("`modules` must be a named list.", call. = FALSE)
  }
  min_high_datasets <- as.integer(min_high_datasets)
  min_medium_datasets <- as.integer(min_medium_datasets)
  if (min_high_datasets < 1L) {
    stop("`min_high_datasets` must be >= 1.", call. = FALSE)
  }
  if (min_medium_datasets < 1L) {
    stop("`min_medium_datasets` must be >= 1.", call. = FALSE)
  }
  missing_files <- files[!file.exists(unname(files))]
  if (length(missing_files)) {
    stop(
      "Missing marker files: ",
      paste(unname(missing_files), collapse = ", "),
      call. = FALSE
    )
  }
  # ========================================================================= #
  # Curated biological categories
  # ========================================================================= #
  references <- gnrh_stage_gene_references()
  known_gnrh_markers <- unique(toupper(c(references$gene, "GNRH1")))
  generic_neuronal <- toupper(c(
    "TUBB","TUBB2A","TUBB2B","TUBB3","TUBA1A","TUBA1B","EEF1A2","ACTG1",
    "PKM","ALDOA","GAPDH","HSP90AB1","HSPA5","HSPH1","MALAT1","MIAT",
    "GNAS","SNAP25","SYT1","RBFOX3"
  ))
  # ========================================================================= #
  # Cross-dataset support
  # ========================================================================= #
  overlap_gene_sets <- results$gene_sets %||% NULL
  if (!is.null(overlap_gene_sets)) {
    overlap_gene_sets <- lapply(
      overlap_gene_sets,
      function(x) unique(toupper(as.character(x)))
    )
  }
  unique_sets <- results$unique %||% list()
  unique_sets <- lapply(
    unique_sets,
    function(x) unique(toupper(as.character(x)))
  )
  # ========================================================================= #
  # Read marker tables
  # ========================================================================= #
  build_one <- function(dataset) {
    marker_file <- files[[dataset]]
    if (!file.exists(marker_file)) {
      warning("Missing marker file: ", marker_file, call. = FALSE)
      return(NULL)
    }
    markers <- utils::read.delim(
      marker_file,
      sep = "\t",
      stringsAsFactors = FALSE,
      check.names = FALSE
    )
    if (!gene_col %in% colnames(markers)) {
      warning("Missing gene column `", gene_col, "` in ", dataset, ".", call. = FALSE)
      return(NULL)
    }
    markers[[gene_col]] <- toupper(trimws(as.character(markers[[gene_col]])))
    markers <- markers[
      !is.na(markers[[gene_col]]) & nzchar(markers[[gene_col]]),
      ,
      drop = FALSE
    ]
    if (!nrow(markers)) {
      return(NULL)
    }
    names(markers)[names(markers) == gene_col] <- "gene"
    markers$dataset <- dataset
    dataset_unique <- unique_sets[[dataset]] %||% character(0)
    markers$is_unique <- markers$gene %in% dataset_unique
    if (!is.null(coexpr_col) && coexpr_col %in% colnames(markers)) {
      markers$coexpr_GNRH1 <- .marker_as_logical(markers[[coexpr_col]])
    } else if ("coexpr_pct" %in% colnames(markers)) {
      x <- suppressWarnings(as.numeric(markers$coexpr_pct))
      markers$coexpr_GNRH1 <- is.finite(x) & x > 0
    } else {
      markers$coexpr_GNRH1 <- NA
    }
    markers$marker_evidence_score <- .marker_evidence_score(markers)
    markers
  }
  marker_list <- lapply(names(files), build_one)
  marker_list <- Filter(Negate(is.null), marker_list)
  if (!length(marker_list)) {
    stop("No marker tables could be loaded.", call. = FALSE)
  }
  all_markers <- do.call(rbind, marker_list)
  rownames(all_markers) <- NULL
  # ========================================================================= #
  # Dataset support
  # ========================================================================= #
  all_genes <- unique(all_markers$gene)
  dataset_support <- vapply(
    all_genes,
    function(gene) {
      if (!is.null(overlap_gene_sets)) {
        sum(vapply(overlap_gene_sets, function(x) gene %in% x, logical(1)))
      } else {
        length(unique(all_markers$dataset[all_markers$gene == gene]))
      }
    },
    integer(1)
  )
  names(dataset_support) <- all_genes
  all_markers$n_datasets <- dataset_support[all_markers$gene]
  all_markers$dataset_fraction <- all_markers$n_datasets / length(files)
  all_markers$reproducible <- all_markers$n_datasets >= min_high_datasets
  all_markers$context_specific <- all_markers$n_datasets == 1L
  # ========================================================================= #
  # Biological status
  # ========================================================================= #
  all_markers$known_status <- ifelse(
    all_markers$gene %in% generic_neuronal,
    "generic_neuronal",
    ifelse(
      all_markers$gene %in% known_gnrh_markers,
      "known_GnRH_or_developmental",
      ifelse(
        all_markers$context_specific,
        "context_specific_candidate",
        "candidate_marker"
      )
    )
  )
  # ========================================================================= #
  # Program annotation
  # ========================================================================= #
  program_df <- .assign_marker_programs(
    genes = all_markers$gene,
    developmental_modules = modules,
    secretory_module = secretory_module
  )
  if (nrow(program_df)) {
    candidate_table <- merge(
      all_markers,
      program_df,
      by = "gene",
      all.x = TRUE,
      sort = FALSE
    )
  } else {
    candidate_table <- all_markers
    candidate_table$program <- NA_character_
    candidate_table$program_dimension <- NA_character_
  }
  candidate_table$program[is.na(candidate_table$program)] <- "unassigned"
  candidate_table$program_dimension[is.na(candidate_table$program_dimension)] <- "unassigned"
  # ========================================================================= #
  # Reference gene
  # ========================================================================= #
  candidate_table$is_reference_gene <- candidate_table$gene == "GNRH1"
  if (!isTRUE(include_gnrh1)) {
    candidate_table <- candidate_table[
      !candidate_table$is_reference_gene,
      ,
      drop = FALSE
    ]
  }
  # ========================================================================= #
  # Confidence
  # ========================================================================= #
  score <- candidate_table$marker_evidence_score
  not_generic <- candidate_table$known_status != "generic_neuronal"
  assigned_program <- candidate_table$program != "unassigned"
  enough_medium_datasets <- candidate_table$n_datasets >= min_medium_datasets
  enough_high_datasets <- candidate_table$n_datasets >= min_high_datasets
  high <- not_generic & assigned_program & enough_high_datasets & score >= min_high_score
  medium <- not_generic & enough_medium_datasets & score >= min_medium_score
  candidate_table$confidence_level <- "low"
  candidate_table$confidence_level[medium] <- "medium"
  candidate_table$confidence_level[high] <- "high"
  candidate_table$confidence_level <- factor(
    candidate_table$confidence_level,
    levels = c("low", "medium", "high"),
    ordered = TRUE
  )
  # ========================================================================= #
  # Integrated score
  # ========================================================================= #
  reproducibility_weight <- 0.5 + candidate_table$dataset_fraction
  program_weight <- ifelse(assigned_program, 1.25, 1)
  coexpr_weight <- ifelse(candidate_table$coexpr_GNRH1 %in% TRUE, 1.10, 1)
  generic_weight <- ifelse(not_generic, 1, 0.25)
  candidate_table$integrated_score <-
    candidate_table$marker_evidence_score *
    reproducibility_weight *
    program_weight *
    coexpr_weight *
    generic_weight
  candidate_table <- candidate_table[
    order(
      -as.integer(candidate_table$confidence_level),
      -candidate_table$n_datasets,
      -candidate_table$integrated_score,
      candidate_table$gene
    ),
    ,
    drop = FALSE
  ]
  rownames(candidate_table) <- NULL
  # ========================================================================= #
  # High-confidence / context-specific
  # ========================================================================= #
  high_confidence <- candidate_table[
    candidate_table$confidence_level == "high" &
      !candidate_table$is_reference_gene,
    ,
    drop = FALSE
  ]
  context_specific <- candidate_table[
    candidate_table$context_specific &
      candidate_table$known_status != "generic_neuronal" &
      !candidate_table$is_reference_gene,
    ,
    drop = FALSE
  ]
  # ========================================================================= #
  # Gene-level consensus
  # ========================================================================= #
  gene_summary <- stats::aggregate(
    cbind(n_datasets, marker_evidence_score, integrated_score) ~ gene,
    data = candidate_table,
    FUN = max,
    na.rm = TRUE
  )
  programs_by_gene <- stats::aggregate(
    program ~ gene,
    data = candidate_table,
    FUN = function(x) {
      x <- sort(unique(x[x != "unassigned"]))
      paste(x, collapse = ", ")
    }
  )
  gene_summary <- merge(
    gene_summary,
    programs_by_gene,
    by = "gene",
    all.x = TRUE,
    sort = FALSE
  )
  gene_summary <- gene_summary[
    order(-gene_summary$n_datasets, -gene_summary$integrated_score),
    ,
    drop = FALSE
  ]
  # ========================================================================= #
  # Program summary
  # ========================================================================= #
  summary_source <- candidate_table[
    candidate_table$confidence_level %in% c("medium", "high") &
      !candidate_table$is_reference_gene,
    ,
    drop = FALSE
  ]
  if (nrow(summary_source)) {
    summary_table <- summary_source |>
      dplyr::group_by(
        .data$program_dimension,
        .data$program,
        .data$confidence_level
      ) |>
      dplyr::summarise(
        n_genes = dplyr::n_distinct(.data$gene),
        genes = paste(sort(unique(.data$gene)), collapse = ", "),
        .groups = "drop"
      )
    split_table <- split(
      summary_source$gene,
      list(summary_source$program_dimension, summary_source$program),
      drop = TRUE
    )
    split_table <- lapply(split_table, function(x) sort(unique(x)))
  } else {
    summary_table <- data.frame(
      program_dimension = character(0),
      program = character(0),
      confidence_level = character(0),
      n_genes = integer(0),
      genes = character(0),
      stringsAsFactors = FALSE
    )
    split_table <- list()
  }
  # ========================================================================= #
  # Dataset summary
  # ========================================================================= #
  dataset_summary <- candidate_table |>
    dplyr::group_by(.data$dataset) |>
    dplyr::summarise(
      n_markers = dplyr::n_distinct(.data$gene),
      n_high = dplyr::n_distinct(.data$gene[.data$confidence_level == "high"]),
      n_medium = dplyr::n_distinct(.data$gene[.data$confidence_level == "medium"]),
      n_context_specific = dplyr::n_distinct(.data$gene[.data$context_specific]),
      .groups = "drop"
    )
  # ========================================================================= #
  # Write output
  # ========================================================================= #
  if (isTRUE(write_output)) {
    out_tables <- file.path(outdir, "tables")
    dir.create(out_tables, recursive = TRUE, showWarnings = FALSE)
    write_tsv <- function(x, filename) {
      utils::write.table(
        x,
        file = file.path(out_tables, filename),
        sep = "\t",
        quote = FALSE,
        row.names = FALSE
      )
    }
    write_tsv(candidate_table, "gnrh_candidate_marker_table.tsv")
    write_tsv(high_confidence, "gnrh_high_confidence_candidate_markers.tsv")
    write_tsv(context_specific, "gnrh_context_specific_candidate_markers.tsv")
    write_tsv(gene_summary, "gnrh_marker_cross_dataset_summary.tsv")
    write_tsv(summary_table, "gnrh_candidate_marker_summary_by_program.tsv")
    write_tsv(dataset_summary, "gnrh_candidate_marker_summary_by_dataset.tsv")
  }
  # ========================================================================= #
  # Return
  # ========================================================================= #
  list(
    candidate_table = candidate_table,
    high_confidence = high_confidence,
    context_specific = context_specific,
    gene_summary = gene_summary,
    summary = summary_table,
    dataset_summary = dataset_summary,
    split_by_program = split_table,
    split_by_dataset_program = split_table,
    modules = list(
      developmental = modules,
      secretory = secretory_module
    ),
    parameters = list(
      min_medium_score = min_medium_score,
      min_high_score = min_high_score,
      min_medium_datasets = min_medium_datasets,
      min_high_datasets = min_high_datasets
    )
  )
}



# ============================================================================= #
# marker-programs.R
# GnRHcell marker-program discovery
# ============================================================================= #


# ============================================================================= #
# Curated programs
# ============================================================================= #

#' Default GnRH developmental marker programs
#'
#' Returns curated gene programs representing major developmental states of
#' the GnRH neuronal lineage.
#'
#' Developmental stage and secretory phenotype are intentionally separated.
#' The developmental programs are \code{identity}, \code{migrating}, and
#' \code{mature}. Secretory machinery is provided separately by
#' \code{\link{gnrh_secretory_marker_module}}.
#'
#' @param include_secretory Logical. Include a \code{secretory} module for
#'   backward compatibility. Default is \code{FALSE}.
#'
#' @return Named list of uppercase gene symbols.
#'
#' @seealso
#' \code{\link{gnrh_secretory_marker_module}},
#' \code{\link{gnrh_marker_programs}},
#' \code{\link{gnrh_stage_gene_references}}
#'

#' @references
#' Wray S. Development of gonadotropin-releasing hormone-1 neurons.
#' Front Neuroendocrinol. 2010.
#'
#' Schwanzel-Fukuda M, Pfaff DW. Origin of luteinizing hormone-releasing
#' hormone neurons. Nature. 1989.
#'
#' Stevenson EL, Corella KM, Chung WCJ. Ontogenesis of
#' gonadotropin-releasing hormone neurons. Front Endocrinol. 2013.
#'
#' Cho HJ, Shan Y, Whittington NC, Wray S. Nasal placode development,
#' GnRH neuronal migration and Kallmann syndrome. Front Cell Dev Biol. 2019.
#'
#' Taroc EZM, Prasad A, Lin JM, Forni PE. GnRH-1 neural migration
#' from the nose to the brain is independent from Slit2, Robo3 and NELL2.
#' Front Cell Neurosci. 2019.
#'
#' Li Q et al. Expression of genes for kisspeptin, neurokinin B and
#' dynorphin in the hypothalamus. Front Endocrinol. 2020.
#'
#' @export
gnrh_stage_modules <- function(
    include_secretory = FALSE
) {
  modules <- list(
    identity = unique(toupper(c(
      "FEZF1",
      "SOX2",
      "HES1",
      "OTX2",
      "SIX3",
      "SIX6",
      "ISL1",
      "DLX1",
      "DLX2",
      "DLX5",
      "DLX6",
      "ARX",
      "FOXG1",
      "RAX",
      "ISL2",
      "MYT1",
      "KLF7",
      "ZIC2",
      "ZIC4",
      "ZIC5",
      "ZNF483",
      "EBF3",
      "MEIS1",
      "ECEL1"
    ))),

    migrating = unique(toupper(c(
      "ANOS1",
      "PROKR2",
      "PROK2",
      "NSMF",
      "DCX",
      "L1CAM",
      "SEMA3A",
      "SEMA3C",
      "SEMA3F",
      "NRP1",
      "NRP2",
      "ROBO1",
      "ROBO2",
      "ROBO3",
      "SLIT1",
      "UNC5D",
      "RIPOR2",
      "PTPRO",
      "PLXNA3",
      "NFASC",
      "ADGRV1",
      "CDH22",
      "CTNNA2",
      "FREM1",
      "CXCR4",
      "GDNF",
      "TMEM131L",
      "DLX6OS1"
    ))),

    mature = unique(toupper(c(
      "KISS1R",
      "GNRHR",
      "DOC2B",
      "PTPRN",
      "BAIAP3",
      "SCG2",
      "SCG5",
      "VGF",
      "HCN1",
      "NALCN",
      "SCN3A",
      "SCN9A",
      "KCNMB2",
      "CACNA1B",
      "CHRNB4",
      "CHRNA3"
    )))
  )

  if (isTRUE(include_secretory))
    modules$secretory <- gnrh_secretory_marker_module()

  modules
}


#' GnRH secretory marker program
#'
#' Returns genes associated with neuroendocrine peptide processing,
#' dense-core vesicles, and regulated secretion.
#'
#' This program represents a functional phenotype rather than a developmental
#' stage.
#'
#' @return Character vector of uppercase gene symbols.
#'
#' @export
gnrh_secretory_marker_module <- function() {
  unique(toupper(c(
    "PCSK1",
    "PCSK2",
    "CPE",
    "CHGA",
    "CHGB",
    "SCG2",
    "SCG5",
    "VGF",
    "SYP",
    "VAMP2",
    "RAB3A",
    "RAB3B",
    "RAB3C",
    "BAIAP3",
    "PTPRN",
    "DOC2B",
    "CADPS",
    "PCSK1N",
    "RAB27B"
  )))
}




#' GnRH developmental and functional marker gene references
#'
#' Returns a gene-level reference table describing curated GnRH developmental
#' and secretory programs.
#'
#' @return Data frame containing gene, program, dimension, evidence class,
#'   and reference information.
#'
#' @export
gnrh_stage_gene_references <- function() {
  developmental <- gnrh_stage_modules()
  secretory <- gnrh_secretory_marker_module()

  modules <- c(
    developmental,
    list(secretory = secretory)
  )

  dimension_map <- c(
    identity = "developmental",
    migrating = "developmental",
    mature = "developmental",
    secretory = "functional"
  )

  evidence_map <- c(
    identity = "developmental_identity",
    migrating = "migration_guidance",
    mature = "neuroendocrine_maturation",
    secretory = "secretory_machinery"
  )

  ref_map <- c(
    identity = paste(
      "Wray 2010;",
      "Stevenson et al. 2013;",
      "Cho et al. 2019"
    ),

    migrating = paste(
      "Schwanzel-Fukuda & Pfaff 1989;",
      "Wray 2010;",
      "Cho et al. 2019;",
      "Taroc et al. 2019"
    ),

    mature = paste(
      "Wray 2010;",
      "Stevenson et al. 2013"
    ),

    secretory = paste(
      "Wray 2010;",
      "general neuroendocrine secretory machinery"
    )
  )

  out <- lapply(
    names(modules),
    function(program) {
      data.frame(
        gene = modules[[program]],
        program = program,
        dimension = dimension_map[[program]],
        evidence_class = evidence_map[[program]],
        references = ref_map[[program]],
        stringsAsFactors = FALSE
      )
    }
  )

  out <- do.call(rbind, out)
  rownames(out) <- NULL

  unique(out)
}



